### Well string

In [1]:
import matplotlib.pyplot as plt
import numpy as np

import timflow.transient as tft

plt.rcParams["font.size"] = 8.0
plt.rcParams["figure.figsize"] = (8, 3)

In [2]:
# T = 500  # transmissivity
# S = 1e-4
# t = np.logspace(-2, 2, 101)
# Q = 1000
# xy=[(-10, 0), (10, 0)]

In [3]:
import timflow.transient as tft
ml = tft.ModelMaq(kaq=[10, 20], z=[20, 10, 8, 0], c=[200], Saq=1e-4, tmin=0.01, tmax=100)
w = tft.Well(ml, 0, 0, tsandQ=[(0, 1000)], rw=0.3, layers=[0,1])
ml.solve()
w.headinside(7)

self.neq  2
solution complete


array([[-5.2164918],
       [-5.2164918]])

In [25]:
import timflow.transient as tft
ml = tft.ModelMaq(kaq=[10, 20], z=[20, 10, 8, 0], c=[200], Saq=1e-4, tmin=0.01, tmax=100)
w = tft.WellString(ml, xy=[(0, 10), (0, -10)], tsandQ=[(0, 1000)], rw=0.3, layers=[0,1])
ml.solve()
w.wlist[0].headinside(7), w.wlist[1].headinside(7)

self.neq  4
solution complete


(array([[-3.93108245],
        [-3.93108245]]),
 array([[-3.93108245],
        [-3.93108245]]))

In [26]:
w.wlist[0].headinside(7)

array([[-3.93108245],
       [-3.93108245]])

In [27]:
w.discharge(7), w.discharge(7)

(array([[384.87942402],
        [615.12057698]]),
 array([[384.87942402],
        [615.12057698]]))

In [18]:
import timflow.transient as tft
ml = tft.ModelMaq(kaq=[10, 20], z=[20, 10, 8, 0], c=[200], Saq=1e-4, tmin=0.01, tmax=100)
w = tft.WellString(ml, xy=[(0, 10), (0, 0), (0, -10)], tsandQ=[(0, 1000)], rw=0.3, layers=[0, 1])
ml.solve()
w.wlist[0].headinside(7), w.wlist[1].headinside(7)

self.neq  6
solution complete


(array([[-3.68444559],
        [-3.68444559]]),
 array([[-3.68444559],
        [-3.68444559]]))

In [19]:
w.discharge_per_well(3)

array([[[137.48595932],
        [110.32977796],
        [137.48595918]],

       [[219.34175437],
        [176.01479935],
        [219.34175423]]])

In [11]:
w.headinside(3)

array([-3.42517577])

In [20]:
import timflow.transient as tft
ml = tft.ModelMaq(kaq=[10, 20, 20], z=[20, 10, 8, 0, -2, -12], c=[200, 100], Saq=1e-4, tmin=0.01, tmax=100)
w = tft.WellString(ml, xy=[(0, 10), (0, 0), (0, -10)], tsandQ=[(0, 1000)], rw=0.3, layers=[1, 2])
ml.solve()
w.wlist[0].headinside(7), w.wlist[1].headinside(7)

self.neq  6
solution complete


(array([[-2.46013965],
        [-2.46013965]]),
 array([[-2.46013965],
        [-2.46013965]]))

In [21]:
w.discharge_per_well(3)

array([[[  0.        ],
        [  0.        ],
        [  0.        ]],

       [[163.1555351 ],
        [131.18099531],
        [163.15553528]],

       [[193.57888274],
        [155.35017301],
        [193.57888319]]])

In [24]:
import timflow.transient as tft
ml = tft.ModelMaq(kaq=[10, 20, 20], z=[20, 10, 8, 0, -2, -12], c=[200, 100], Saq=1e-4, tmin=0.01, tmax=100)
w = tft.WellString(ml, xy=[(0, 10), (0, 0), (0, -10)], tsandQ=[(0, 1000)], rw=0.3, layers=[1, 2], res=0.2)
ml.solve()
w.wlist[0].headinside(7), w.wlist[1].headinside(7)

self.neq  6
solution complete


(array([[-4.429406],
        [-4.429406]]),
 array([[-4.429406],
        [-4.429406]]))